-- Run these commands in your Supabase SQL Editor

-- 1. Student Permissions (Tracks Diagnostic & Chapter Completion)
CREATE TABLE IF NOT EXISTS student_permissions (
    student_id TEXT PRIMARY KEY,
    has_taken_diagnostic BOOLEAN DEFAULT FALSE,
    completed_chapters TEXT DEFAULT '[]', -- Stores JSON array e.g. ["Force", "Motion"]
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Performance History (Granular Log of Every Question)
    CREATE TABLE IF NOT EXISTS performance_history (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_id TEXT NOT NULL,
        content_id TEXT, -- The UUID of the question
        accuracy FLOAT DEFAULT 0.0,
        time_spent FLOAT DEFAULT 0.0,
        difficulty_level INTEGER DEFAULT 0,
        chapter TEXT,
        topic TEXT,
        outcome TEXT, -- "ADVANCE", "RETRY", "COMPLETE"
        reward_score FLOAT DEFAULT 0.0,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );

-- 3. RL States (Current Adaptive State per Student)
CREATE TABLE IF NOT EXISTS rl_states (
    student_id TEXT PRIMARY KEY,
    topic_mastery FLOAT DEFAULT 0.0,
    avg_accuracy_last_5 FLOAT DEFAULT 0.0,
    avg_time_per_question FLOAT DEFAULT 0.0,
    total_attempts INTEGER DEFAULT 0,
    current_difficulty_index INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Students (If not already created)
CREATE TABLE IF NOT EXISTS students (
    id TEXT PRIMARY KEY, -- Firebase/Auth UID
    email TEXT,
    grade INTEGER DEFAULT 9,
    attempts INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
