"""
Classify and validate question types
Simplified for Gemini integration
"""

def classify_type(state: dict) -> dict:
    """
    LangGraph node: Validate question types generated by Gemini
    """
    questions = state.get("questions", [])
    
    for q in questions:
        # Gemini provides types, we just ensure detected_type is present
        if "detected_type" not in q:
            q["detected_type"] = q.get("type", "unknown")
            
        q["validated"] = True
    
    print(f"Validated {len(questions)} Gemini-generated questions")
    return state
